apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-stable
  labels:
    app: ci-cd-demo
    track: stable
spec:
  replicas: {{ .Values.replicaCount.stable }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ci-cd-demo
      track: stable
  template:
    metadata:
      labels:
        app: ci-cd-demo
        track: stable
    spec:
      containers:
        - name: ci-cd-demo
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
